name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # gives semantic-release access to all previous commits
          token: ${{ secrets.GITHUB_TOKEN }} # admin token
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.19.0
      - name: Install dependencies
        run: yarn
      - name: Cut release
        run: yarn release
